FROM %DOCKER_FROM

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /root
ENV HOME /root

RUN echo "%VERSION_INFO" >> VERSION_INFO

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y build-essential git
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.6
RUN apt-get install -y python3-pip


RUN pip3 install --upgrade pip
RUN pip3 install pyyaml
RUN pip3 install mlperf_compliance

ADD . /root

%%GIT_CHECKOUT
%%DOCKER_SCRIPT

ENTRYPOINT ["/bin/bash"]

